import Link from "next/link";

const effectiveDate = "19 July 2026";

export default function PrivacyPage() {
  return <main className="min-h-screen bg-[#edf3f2] px-5 py-10 text-ink sm:px-8 lg:px-10"><article className="mx-auto max-w-3xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-10"><Link className="text-sm font-bold text-teal underline underline-offset-4" href="/">← Back to Scht</Link><p className="mt-8 text-sm font-bold tracking-[.12em] text-teal">LEGAL</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Privacy Policy</h1><p className="mt-3 text-sm text-slate-600">Effective {effectiveDate}</p><div className="mt-8 space-y-8 leading-7 text-slate-700">
    <p>Scht is an invite-only academic workspace. This policy explains what information the service handles, why it handles it, and the choices available to students who use it.</p>
    <Section title="Information Scht handles"><ul><li><strong>Account information:</strong> the email address and basic profile information supplied through Supabase authentication.</li><li><strong>Workspace information:</strong> academic terms, subjects, tasks, grades, notes, projects, and syllabus files a student chooses to add.</li><li><strong>Connected-service information:</strong> read-only Google Calendar events, unread Gmail message subjects/snippets, and Canvas courses/assignments only after the student explicitly connects each service.</li><li><strong>AI information:</strong> planning prompts and reviewed proposals. A user’s AI provider key is encrypted in the browser with the user’s passphrase before it is stored.</li><li><strong>Delivery information:</strong> reminder preferences and Apps Script delivery records for optional email reminders.</li></ul></Section>
    <Section title="How Scht uses information"><p>Scht uses this information to authenticate invited users, show their planning workspace, import information they request from connected services, calculate academic progress, deliver requested reminders, prevent misuse, and operate the owner-admin tools. Scht does not sell personal information or use connected-service data for advertising.</p></Section>
    <Section title="When information is shared"><p>Scht uses service providers to operate the app: Supabase for authentication and database/storage, Vercel for hosting, and Google/Canvas only when a student connects those services. An AI prompt is sent only to the provider selected by the student. The optional Apps Script companion receives only the prepared email job needed to send a reminder; it does not receive Google OAuth, Canvas, or Supabase credentials.</p></Section>
    <Section title="Google data"><p>Google Calendar and Gmail access is read-only and requested only after a user chooses Connect Google. Calendar events and unread Gmail subjects/snippets are used only to create the user’s Scht timeline or follow-up tasks. A user can revoke Google access from their Google Account permissions and can ask the Scht owner administrator to remove their workspace data.</p></Section>
    <Section title="Retention and security"><p>Workspace information is retained while the account remains active, subject to legitimate operational, security, and backup needs. Scht uses access controls, encrypted integration credentials, and browser-side encryption for saved AI keys. No online service can promise absolute security; users should keep their passphrases and connected-service credentials private.</p></Section>
    <Section title="Your choices and rights"><p>Users can choose whether to connect Google, Canvas, or an AI provider, and can disable reminder email in Settings. To request access, correction, export, or deletion of account data, contact the Scht owner administrator who issued the invite. Students in the Philippines may also have rights under the Data Privacy Act of 2012, including rights to be informed, access, correct, object, erase/block, and complain to the National Privacy Commission.</p></Section>
    <Section title="Changes and contact"><p>Material changes to this policy will be posted on this page with an updated effective date. For questions or data requests, contact the Scht owner administrator associated with your invitation before using the service.</p></Section>
  </div><div className="mt-10 flex gap-5 border-t border-slate-200 pt-6 text-sm font-bold text-teal"><Link href="/terms">Terms of Service</Link><a href="https://privacy.gov.ph/data-subject-rights/" rel="noreferrer" target="_blank">Data subject rights</a></div></article></main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-black text-ink">{title}</h2><div className="mt-2 space-y-3">{children}</div></section>; }
