import Link from "next/link";

export default function TermsPage() {
  return <main className="min-h-screen bg-[#edf3f2] px-5 py-10 text-ink sm:px-8 lg:px-10"><article className="mx-auto max-w-3xl rounded-[2rem] bg-white p-6 shadow-sm sm:p-10"><Link className="text-sm font-bold text-teal underline underline-offset-4" href="/">← Back to Scht</Link><p className="mt-8 text-sm font-bold tracking-[.12em] text-teal">LEGAL</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Terms of Service</h1><p className="mt-3 text-sm text-slate-600">Effective 19 July 2026</p><div className="mt-8 space-y-8 leading-7 text-slate-700">
    <Section title="Using Scht"><p>Scht is an invite-only planning tool for individual students. By creating or using an account, you agree to use it lawfully, protect your sign-in link and connected-service credentials, and provide information you are entitled to use. Access may be limited to users invited by an owner administrator.</p></Section>
    <Section title="Your academic decisions"><p>Scht organizes information and calculates QPI/GPA estimates from information entered or approved by the user. It does not replace official university records, course syllabi, faculty guidance, or academic judgment. Verify important deadlines, grades, and calculations with the original source.</p></Section>
    <Section title="Connected services and AI"><p>You choose whether to connect Google, Canvas, Apps Script reminders, or an AI provider. You are responsible for complying with your institution’s policies and each provider’s terms. AI suggestions are proposals only; Scht does not apply them until you explicitly review and confirm them.</p></Section>
    <Section title="Content and availability"><p>You retain responsibility for the information you add. Do not upload content that is unlawful, harmful, or violates another person’s rights. The service may change, be paused for maintenance, or be restricted when necessary for security, legal compliance, or misuse prevention.</p></Section>
    <Section title="Ending access"><p>You may stop using Scht at any time. The owner administrator may suspend or remove access for misuse, expired invitations, or operational reasons. To request account-data deletion, contact the owner administrator who issued the invitation.</p></Section>
    <Section title="Disclaimers and changes"><p>Scht is provided as an educational planning tool. To the extent permitted by law, it is provided without a guarantee that it will be uninterrupted or error-free. Material changes to these terms will be posted here with an updated effective date.</p></Section>
  </div><div className="mt-10 flex gap-5 border-t border-slate-200 pt-6 text-sm font-bold text-teal"><Link href="/privacy">Privacy Policy</Link><Link href="/get-started">Secure access</Link></div></article></main>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-black text-ink">{title}</h2><div className="mt-2">{children}</div></section>; }
