'use client';

import { FormEvent, useState } from 'react';

type Profile = { id: string; display_name: string | null };

export function AdminControls({ profiles }: { profiles: Profile[] }) {
  const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [userId, setUserId] = useState(profiles[0]?.id ?? '');
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); const response = await fetch('/api/admin/invites', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: form.get('email'), role: form.get('role'), expiresAt: form.get('expiresAt') || null }) }); const body = await response.json() as { error?: string; invite?: { email: string } }; setNotice(response.ok ? `Invite created for ${body.invite?.email}.` : body.error ?? 'Could not create invite.'); setBusy(false); if (response.ok) event.currentTarget.reset(); }
  function downloadExport() { if (userId) window.location.assign(`/api/admin/export?userId=${encodeURIComponent(userId)}`); }
  return <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Invite a user</h2><form className="mt-4 space-y-3" onSubmit={invite}><label className="block text-sm font-semibold">Email<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" name="email" required type="email" /></label><label className="block text-sm font-semibold">Role<select className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" name="role"><option value="member">Member</option><option value="owner_admin">Owner admin</option></select></label><label className="block text-sm font-semibold">Expiry (optional)<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" name="expiresAt" type="datetime-local" /></label><button className="rounded-xl bg-action px-4 py-2 font-bold text-white disabled:opacity-60" disabled={busy} type="submit">Create invite</button></form></article><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Export a user’s data</h2><p className="mt-1 text-sm text-slate-600">Downloads the selected workspace as JSON. The export action is written to the audit log.</p><label className="mt-4 block text-sm font-semibold">User<select className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" onChange={(event) => setUserId(event.target.value)} value={userId}>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.display_name || profile.id}</option>)}</select></label><button className="mt-3 rounded-xl border border-teal px-4 py-2 font-bold text-teal disabled:opacity-60" disabled={!userId} onClick={downloadExport} type="button">Download JSON export</button></article>{notice && <p className="text-sm text-slate-700" role="status">{notice}</p>}</section>;
}
