'use client';

import { FormEvent, useState } from 'react';

type Task = { id: string; title: string; due_at: string | null };
type Preference = { timezone: string; quiet_start: string | null; quiet_end: string | null; enabled: boolean } | null;

export function ReminderPanel({ preference, tasks }: { preference: Preference; tasks: Task[] }) {
  const [enabled, setEnabled] = useState(preference?.enabled ?? true); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); const response = await fetch('/api/reminders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ enabled, timezone: form.get('timezone'), quietStart: form.get('quietStart') || null, quietEnd: form.get('quietEnd') || null }) }); const body = await response.json() as { error?: string }; setNotice(response.ok ? 'Reminder preferences saved.' : body.error ?? 'Could not save preferences.'); setBusy(false); }
  async function queue(taskId: string) { setBusy(true); const response = await fetch('/api/reminders', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ taskId }) }); const body = await response.json() as { error?: string; sendAt?: string }; setNotice(response.ok ? `Reminder scheduled for ${body.sendAt ? new Date(body.sendAt).toLocaleString() : 'your task deadline'}.` : body.error ?? 'Could not schedule reminder.'); setBusy(false); }
  return <section className="mt-5 max-w-5xl rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Email reminders</h2><p className="mt-1 text-sm text-slate-600">Choose your delivery window, then schedule a reminder for any task with a due date. Delivery is handled by the protected Apps Script companion.</p><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={save}><label className="text-sm font-semibold">Time zone<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" defaultValue={preference?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone} name="timezone" required /></label><label className="flex items-center gap-2 self-end pb-2 text-sm font-semibold"><input checked={enabled} onChange={(event) => setEnabled(event.target.checked)} type="checkbox" /> Enable email reminders</label><label className="text-sm font-semibold">Quiet hours start<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" defaultValue={preference?.quiet_start?.slice(0, 5) ?? ''} name="quietStart" type="time" /></label><label className="text-sm font-semibold">Quiet hours end<input className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2" defaultValue={preference?.quiet_end?.slice(0, 5) ?? ''} name="quietEnd" type="time" /></label><button className="rounded-xl border border-teal px-4 py-2 font-bold text-teal disabled:opacity-60 sm:col-span-2" disabled={busy} type="submit">Save delivery preferences</button></form><div className="mt-5"><h3 className="font-bold">Schedule a task reminder</h3><ul className="mt-2 space-y-2">{tasks.map((task) => <li className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3" key={task.id}><span className="text-sm"><strong>{task.title}</strong><br />Due {task.due_at ? new Date(task.due_at).toLocaleString() : 'unscheduled'}</span><button className="rounded-lg bg-teal px-3 py-1.5 text-sm font-bold text-white disabled:opacity-60" disabled={busy || !enabled} onClick={() => void queue(task.id)} type="button">Schedule</button></li>)}{!tasks.length && <li className="text-sm text-slate-600">No open tasks with due dates to schedule.</li>}</ul></div>{notice && <p className="mt-3 text-sm text-slate-700" role="status">{notice}</p>}</section>;
}
